<?php
namespace Diolan12;

/**
 * PHP Lorem Ipsum generator
 * Github [diolan12\php-lipsum](https://github.com/diolan12/php-lipsum)
 */
class LoremIpsum
{
    private $paragraphs = [
        "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas mollis vehicula urna, ac dictum turpis vulputate rutrum. Nulla pharetra massa ligula, a malesuada nibh vehicula nec. Morbi rhoncus sagittis accumsan. Nulla lacinia ex a vehicula cursus. Nunc pulvinar finibus pulvinar. Maecenas eleifend ut sapien a pellentesque. Vestibulum justo purus, tristique quis enim et, dignissim volutpat arcu. Aliquam erat volutpat. In hac habitasse platea dictumst. Nulla et malesuada turpis, ac finibus enim. Fusce non arcu ut est imperdiet mollis. Mauris ultrices purus a tortor consequat rhoncus. Sed eu lacus ac odio fermentum ullamcorper ac rutrum ipsum. Vestibulum lobortis dolor pretium aliquet mollis. Curabitur euismod ante commodo neque ornare, in semper nunc gravida. Ut pretium tellus pulvinar dolor lacinia, vel pretium lacus dictum.",
        "Pellentesque lacinia iaculis erat quis dictum. Morbi mattis orci vel aliquam fringilla. Etiam hendrerit dictum orci, ac rutrum ligula porta quis. Aliquam volutpat arcu non ipsum lacinia, a fringilla lacus interdum. Nulla non iaculis mi. Morbi auctor, nisl malesuada consectetur cursus, enim ante gravida tortor, ac semper risus orci vitae enim. Vivamus vitae nisl commodo, dictum ex vel, lacinia erat. Donec ut sem quis purus sodales tempus. Nulla condimentum ex eget tellus rhoncus, eu dignissim diam congue. Fusce enim ante, pretium ut porta vel, accumsan sit amet velit. Curabitur suscipit et mauris sit amet rutrum.",
        "Nunc venenatis et nisl ac porta. Nunc cursus sed est ac efficitur. Nulla in lacinia enim. Donec pellentesque tellus ex, vitae elementum eros malesuada ut. Morbi varius neque faucibus lorem cursus, quis scelerisque odio mollis. Fusce consectetur, augue et iaculis dignissim, urna augue gravida sapien, in consequat quam ante non enim. Vestibulum ultricies risus nec tincidunt sagittis. Quisque in lacus varius, vehicula elit porta, tincidunt quam. Sed tempor enim eget ex tincidunt bibendum. Sed sit amet elementum ipsum, nec suscipit dui. Quisque venenatis bibendum lacus ut bibendum. Pellentesque lacinia condimentum sem vel lacinia. Etiam volutpat diam vitae elit blandit, et mollis dolor bibendum.",
        "Curabitur pulvinar leo in sem facilisis ullamcorper. Aliquam faucibus nec turpis eu sagittis. Mauris a nunc sed massa volutpat bibendum sit amet a elit. Nullam non arcu vestibulum, interdum mauris in, maximus mauris. Mauris et ante lacinia justo luctus pellentesque eget id orci. Ut at ligula orci. Quisque et blandit ipsum. Donec lobortis, purus congue porta imperdiet, lacus ante tincidunt odio, nec pharetra neque odio non mauris. In imperdiet dui sit amet nisl egestas pulvinar eu sit amet ipsum. Nam elementum turpis vitae fringilla varius. Maecenas auctor, lectus ac malesuada venenatis, elit dolor ornare quam, at bibendum magna lectus id lorem. Phasellus eget sapien eget lectus aliquet semper ac at odio. Nulla at dictum tellus, vel commodo ante. Duis efficitur vehicula sapien quis placerat. Vestibulum at nunc interdum, vulputate mi at, aliquam dui. Morbi feugiat nunc in turpis tempor, eget sollicitudin urna ornare.",
        "Sed magna ipsum, auctor sit amet commodo sit amet, suscipit ut nibh. Donec aliquam dolor at euismod fringilla. Morbi non vehicula neque, ut efficitur erat. In nec purus tincidunt, posuere odio eu, venenatis sem. Sed vitae erat et elit interdum tincidunt. Nullam a leo nibh. Nulla facilisi. Maecenas eu orci lacus. Phasellus dignissim tortor et dolor fermentum, eu tempus ipsum molestie. Integer gravida mattis tempor. Praesent et mauris eu tortor blandit congue."
    ];

    private $sentences = [
        //p1
        "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
        "Maecenas mollis vehicula urna, ac dictum turpis vulputate rutrum.",
        "Nulla pharetra massa ligula, a malesuada nibh vehicula nec.",
        "Morbi rhoncus sagittis accumsan.",
        "Nulla lacinia ex a vehicula cursus.",
        "Nunc pulvinar finibus pulvinar.",
        "Maecenas eleifend ut sapien a pellentesque.",
        "Vestibulum justo purus, tristique quis enim et, dignissim volutpat arcu.",
        "Aliquam erat volutpat.",
        "In hac habitasse platea dictumst.",
        "Nulla et malesuada turpis, ac finibus enim.",
        "Fusce non arcu ut est imperdiet mollis.",
        "Mauris ultrices purus a tortor consequat rhoncus.",
        "Sed eu lacus ac odio fermentum ullamcorper ac rutrum ipsum.",
        "Vestibulum lobortis dolor pretium aliquet mollis.",
        "Curabitur euismod ante commodo neque ornare, in semper nunc gravida.",
        "Ut pretium tellus pulvinar dolor lacinia, vel pretium lacus dictum.",

        // p2
        "Pellentesque lacinia iaculis erat quis dictum.",
        "Morbi mattis orci vel aliquam fringilla.",
        "Etiam hendrerit dictum orci, ac rutrum ligula porta quis.",
        "Aliquam volutpat arcu non ipsum lacinia, a fringilla lacus interdum.",
        "Nulla non iaculis mi.",
        "Morbi auctor, nisl malesuada consectetur cursus, enim ante gravida tortor, ac semper risus orci vitae enim.",
        "Vivamus vitae nisl commodo, dictum ex vel, lacinia erat.",
        "Donec ut sem quis purus sodales tempus.",
        "Nulla condimentum ex eget tellus rhoncus, eu dignissim diam congue.",
        "Fusce enim ante, pretium ut porta vel, accumsan sit amet velit.",
        "Curabitur suscipit et mauris sit amet rutrum.",

        // p3
        "Nunc venenatis et nisl ac porta.",
        "Nunc cursus sed est ac efficitur.",
        "Nulla in lacinia enim.",
        "Donec pellentesque tellus ex, vitae elementum eros malesuada ut.",
        "Morbi varius neque faucibus lorem cursus, quis scelerisque odio mollis.",
        "Fusce consectetur, augue et iaculis dignissim, urna augue gravida sapien, in consequat quam ante non enim.",
        "Vestibulum ultricies risus nec tincidunt sagittis.",
        "Quisque in lacus varius, vehicula elit porta, tincidunt quam.",
        "Sed tempor enim eget ex tincidunt bibendum.",
        "Sed sit amet elementum ipsum, nec suscipit dui.",
        "Quisque venenatis bibendum lacus ut bibendum.",
        "Pellentesque lacinia condimentum sem vel lacinia.",
        "Etiam volutpat diam vitae elit blandit, et mollis dolor bibendum.",

        //p4
        "Curabitur pulvinar leo in sem facilisis ullamcorper.",
        "Aliquam faucibus nec turpis eu sagittis.",
        "Mauris a nunc sed massa volutpat bibendum sit amet a elit.",
        "Nullam non arcu vestibulum, interdum mauris in, maximus mauris.",
        "Mauris et ante lacinia justo luctus pellentesque eget id orci.",
        "Ut at ligula orci.",
        "Quisque et blandit ipsum.",
        "Donec lobortis, purus congue porta imperdiet, lacus ante tincidunt odio, nec pharetra neque odio non mauris.",
        "In imperdiet dui sit amet nisl egestas pulvinar eu sit amet ipsum.",
        "Nam elementum turpis vitae fringilla varius.",
        "Maecenas auctor, lectus ac malesuada venenatis, elit dolor ornare quam, at bibendum magna lectus id lorem.",
        "Phasellus eget sapien eget lectus aliquet semper ac at odio.",
        "Nulla at dictum tellus, vel commodo ante.",
        "Duis efficitur vehicula sapien quis placerat.",
        "Vestibulum at nunc interdum, vulputate mi at, aliquam dui.",
        "Morbi feugiat nunc in turpis tempor, eget sollicitudin urna ornare.",

        //p5
        "Sed magna ipsum, auctor sit amet commodo sit amet, suscipit ut nibh.",
        "Donec aliquam dolor at euismod fringilla.",
        "Morbi non vehicula neque, ut efficitur erat.",
        "In nec purus tincidunt, posuere odio eu, venenatis sem.",
        "Sed vitae erat et elit interdum tincidunt.",
        "Nullam a leo nibh.",
        "Nulla facilisi.",
        "Maecenas eu orci lacus.",
        "Phasellus dignissim tortor et dolor fermentum, eu tempus ipsum molestie.",
        "Integer gravida mattis tempor.",
        "Praesent et mauris eu tortor blandit congue.",
    ];

    private $words = [
        //p1
        "Lorem",
        "ipsum",
        "dolor",
        "sit",
        "amet,",
        "consectetur",
        "adipiscing",
        "elit.",
        "Maecenas",
        "mollis",
        "vehicula",
        "urna,",
        "ac",
        "dictum",
        "turpis",
        "vulputate",
        "rutrum.",
        "Nulla",
        "pharetra",
        "massa",
        "ligula,",
        "a",
        "malesuada",
        "nibh",
        "vehicula",
        "nec.",
        "Morbi",
        "rhoncus",
        "sagittis",
        "accumsan.",
        "Nulla",
        "lacinia",
        "ex",
        "a",
        "vehicula",
        "cursus.",
        "Nunc",
        "pulvinar",
        "finibus",
        "pulvinar.",
        "Maecenas",
        "eleifend",
        "ut",
        "sapien",
        "a",
        "pellentesque.",
        "Vestibulum",
        "justo",
        "purus,",
        "tristique",
        "quis",
        "enim",
        "et,",
        "dignissim",
        "volutpat",
        "arcu.",
        "Aliquam",
        "erat",
        "volutpat.",
        "In",
        "hac",
        "habitasse",
        "platea",
        "dictumst.",
        "Nulla",
        "et",
        "malesuada",
        "turpis,",
        "ac",
        "finibus",
        "enim.",
        "Fusce",
        "non",
        "arcu",
        "ut",
        "est",
        "imperdiet",
        "mollis.",
        "Mauris",
        "ultrices",
        "purus",
        "a",
        "tortor",
        "consequat",
        "rhoncus.",
        "Sed",
        "eu",
        "lacus",
        "ac",
        "odio",
        "fermentum",
        "ullamcorper",
        "ac",
        "rutrum",
        "ipsum.",
        "Vestibulum",
        "lobortis",
        "dolor",
        "pretium",
        "aliquet",
        "mollis.",
        "Curabitur",
        "euismod",
        "ante",
        "commodo",
        "neque",
        "ornare,",
        "in",
        "semper",
        "nunc",
        "gravida.",
        "Et",
        "pretium",
        "tellus",
        "pulvinar",
        "dolor",
        "lacinia,",
        "vel",
        "pretium",
        "lacus",
        "dictum.",

        //p2
        "Pellentesque",
        "lacinia",
        "iaculis",
        "erat",
        "quis",
        "dictum.",
        "Morbi",
        "mattis",
        "orci",
        "vel",
        "aliquam",
        "fringilla.",
        "Etiam",
        "hendrerit",
        "dictum",
        "orci,",
        "ac",
        "rutrum",
        "ligula",
        "porta",
        "quis.",
        "Aliquam",
        "volutpat",
        "arcu",
        "non",
        "ipsum",
        "lacinia,",
        "a",
        "fringilla",
        "lacus",
        "interdum.",
        "Nulla",
        "non",
        "iaculis",
        "mi.",
        "Morbi",
        "auctor,",
        "nisl",
        "malesuada",
        "consectetur",
        "cursus,",
        "enim",
        "ante",
        "gravida",
        "tortor,",
        "ac",
        "semper",
        "risus",
        "orci",
        "vitae",
        "enim.",
        "Vivamus",
        "vitae",
        "nisl",
        "commodo,",
        "dictum",
        "ex",
        "vel,",
        "lacinia",
        "erat.",
        "Donec",
        "ut",
        "sem",
        "quis",
        "purus",
        "sodales",
        "tempus.",
        "Nulla",
        "condimentum",
        "ex",
        "eget",
        "tellus",
        "rhoncus,",
        "eu",
        "dignissim",
        "diam",
        "congue.",
        "Fusce",
        "enim",
        "ante,",
        "pretium",
        "ut",
        "porta",
        "vel,",
        "accumsan",
        "sit",
        "amet",
        "velit.",
        "Curabitur",
        "suscipit",
        "et",
        "mauris",
        "sit",
        "amet",
        "rutrum.",

        //p3
        "Nunc",
        "venenatis",
        "et",
        "nisl",
        "ac",
        "porta.",
        "Nunc",
        "cursus",
        "sed",
        "est",
        "ac",
        "efficitur.",
        "Nulla",
        "in",
        "lacinia",
        "enim.",
        "Donec",
        "pellentesque",
        "tellus",
        "ex,",
        "vitae",
        "elementum",
        "eros",
        "malesuada",
        "ut.",
        "Morbi",
        "varius",
        "neque",
        "faucibus",
        "lorem",
        "cursus,",
        "quis",
        "scelerisque",
        "odio",
        "mollis.",
        "Fusce",
        "consectetur,",
        "augue",
        "et",
        "iaculis",
        "dignissim,",
        "urna",
        "augue",
        "gravida",
        "sapien,",
        "in",
        "consequat",
        "quam",
        "ante",
        "non",
        "enim.",
        "Vestibulum",
        "ultricies",
        "risus",
        "nec",
        "tincidunt",
        "sagittis.",
        "Quisque",
        "in",
        "lacus",
        "varius,",
        "vehicula",
        "elit",
        "porta,",
        "tincidunt",
        "quam.",
        "Sed",
        "tempor",
        "enim",
        "eget",
        "ex",
        "tincidunt",
        "bibendum.",
        "Sed",
        "sit",
        "amet",
        "elementum",
        "ipsum,",
        "nec",
        "suscipit",
        "dui.",
        "Quisque",
        "venenatis",
        "bibendum",
        "lacus",
        "ut",
        "bibendum.",
        "Pellentesque",
        "lacinia",
        "condimentum",
        "sem",
        "vel",
        "lacinia.",
        "Etiam",
        "volutpat",
        "diam",
        "vitae",
        "elit",
        "blandit,",
        "et",
        "mollis",
        "dolor",
        "bibendum.",

        //p4
        "Curabitur",
        "pulvinar",
        "leo",
        "in",
        "sem",
        "facilisis",
        "ullamcorper.",
        "Aliquam",
        "faucibus",
        "nec",
        "turpis",
        "eu",
        "sagittis.",
        "Mauris",
        "a",
        "nunc",
        "sed",
        "massa",
        "volutpat",
        "bibendum",
        "sit",
        "amet",
        "a",
        "elit.",
        "Nullam",
        "non",
        "arcu",
        "vestibulum,",
        "interdum",
        "mauris",
        "in,",
        "maximus",
        "mauris.",
        "Mauris",
        "et",
        "ante",
        "lacinia",
        "justo",
        "luctus",
        "pellentesque",
        "eget",
        "id",
        "orci.",
        "Ut",
        "at",
        "ligula",
        "orci.",
        "Quisque",
        "et",
        "blandit",
        "ipsum.",
        "Donec",
        "lobortis,",
        "purus",
        "congue",
        "porta",
        "imperdiet,",
        "lacus",
        "ante",
        "tincidunt",
        "odio,",
        "nec",
        "pharetra",
        "neque",
        "odio",
        "non",
        "mauris.",
        "In",
        "imperdiet",
        "dui",
        "sit",
        "amet",
        "nisl",
        "egestas",
        "pulvinar",
        "eu",
        "sit",
        "amet",
        "ipsum.",
        "Nam",
        "elementum",
        "turpis",
        "vitae",
        "fringilla",
        "varius.",
        "Maecenas",
        "auctor,",
        "lectus",
        "ac",
        "malesuada",
        "venenatis,",
        "elit",
        "dolor",
        "ornare",
        "quam,",
        "at",
        "bibendum",
        "magna",
        "lectus",
        "id",
        "lorem.",
        "Phasellus",
        "eget",
        "sapien",
        "eget",
        "lectus",
        "aliquet",
        "semper",
        "ac",
        "at",
        "odio.",
        "Nulla",
        "at",
        "dictum",
        "tellus,",
        "vel",
        "commodo",
        "ante.",
        "Duis",
        "efficitur",
        "vehicula",
        "sapien",
        "quis",
        "placerat.",
        "Vestibulum",
        "at",
        "nunc",
        "interdum,",
        "vulputate",
        "mi",
        "at,",
        "aliquam",
        "dui.",
        "Morbi",
        "feugiat",
        "nunc",
        "in",
        "turpis",
        "tempor,",
        "eget",
        "sollicitudin",
        "urna",
        "ornare.",

        // p5
        "Sed",
        "magna",
        "ipsum,",
        "auctor",
        "sit",
        "amet",
        "commodo",
        "sit",
        "amet,",
        "suscipit",
        "ut",
        "nibh.",
        "Donec",
        "aliquam",
        "dolor",
        "at",
        "euismod",
        "fringilla.",
        "Morbi",
        "non",
        "vehicula",
        "neque,",
        "ut",
        "efficitur",
        "erat.",
        "In",
        "nec",
        "purus",
        "tincidunt,",
        "posuere",
        "odio",
        "eu,",
        "venenatis",
        "sem.",
        "Sed",
        "vitae",
        "erat",
        "et",
        "elit",
        "interdum",
        "tincidunt.",
        "Nullam",
        "a",
        "leo",
        "nibh.",
        "Nulla",
        "facilisi.",
        "Maecenas",
        "eu",
        "orci",
        "lacus.",
        "Phasellus",
        "dignissim",
        "tortor",
        "et",
        "dolor",
        "fermentum,",
        "eu",
        "tempus",
        "ipsum",
        "molestie.",
        "Integer",
        "gravida",
        "mattis",
        "tempor.",
        "Praesent",
        "et",
        "mauris",
        "eu",
        "tortor",
        "blandit",
        "congue."
    ];

    private $wrap = null;

    /**
     * Get LoremIpsum's instance
     * @return \Diolan12\LoremIpsum
     */
    public static function instance()
    {
        return new self();
    }

    /**
     * Builds result with wrapper.
     *
     * @param string $string result.
     * @return string
     */
    private function build($string)
    {
        if ($this->wrap == null) {
            return $string;
        }
        return "<$this->wrap>$string</$this->wrap>";
    }

    /**
     * Add an HTML element wrap to the generated string.
     *
     * @param string $wrap HTML wrapper element.
     * @return \Diolan12\LoremIpsum
     */
    public function wrap($wrap = 'p')
    {
        $this->wrap = strtolower(preg_replace('/[\W]/', '', $wrap));
        return $this;
    }


    /**
     * Generate lorem ipsum words.
     *
     * @param int $length Length of the words (default 2).
     * @param string $separator Separator on each paragraphs (default space).
     * @return string
     */
    public function words($length = 2, $separator = " ")
    {
        return $this->build(implode($separator, array_slice($this->words, 0, $length)));
    }


    /**
     * Generate lorem ipsum sentences.
     *
     * @param int $length Length of the words (default 1).
     * @param string $separator Separator on each paragraphs (default space).
     * @return string
     */
    public function sentences($length = 1, $separator = " ")
    {
        return $this->build(implode($separator, array_slice($this->sentences, 0, $length)));
    }


    /**
     * Generate lorem ipsum paragraphs.
     *
     * @param int $length Length of the paragraphs (default 1).
     * @param string $separator Separator on each paragraphs (default \n).
     * @return string
     */
    public function paragraphs($length = 1, $separator = null)
    {
        if ($separator == null) {
            return $this->build(implode("\n", array_slice($this->paragraphs, 0, $length)));
        }
        return $this->build(implode($separator, array_slice($this->paragraphs, 0, $length)));
    }

}
